config/routes.rb
Rails.application.routes.draw do
  # get 'songs/index'
  #
  # get 'songs/new'
  #
  # get 'songs/edit'
  #
  # get 'songs/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "artists#index"

resources :artists
resources :songs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true
  has_many :songs, dependent: :destroy

  def self.order_by_name
    order(:name)
  end

  def self.order_by_name_desc
    order(:name).reverse
  end

  def self.order_by_created
    order(:created_at)
  end

  def self.order_by_created_desc
    order(:created_at).reverse
  end

end

app/models/song.rb
class Song < ApplicationRecord
  validates :name, presence: true
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  # GET /todos
  # GET /todos.json
  def index
    # @artists = Artist.order_by_name
    if params[:sort]
      # @artists = Artist.order(params[:sort] + " " + params[:direction])
      @artists = Artist.order ("#{params[:sort]} #{params[:direction]}")
    else
      @artists = Artist.order_by_name
    end
  end

  def show
    @artist = Artist.find(params[:id])
    @songs = @artist.songs
    @song = Song.new
    respond_to do |format|
      format.html
      format.json
    end
  end


  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new( artist_params )

    if @artist.save
      redirect_to artist_path(@artist), notice: "Artist succesfully created"
    else
      render :new
    end
  end


  def edit
    @artist = Artist.find[:id]
  end

  def update
    if @artist.update( artist_params )
      redirect_to artist_path(@artist), notice: "Artist succesfully updated"
    else
      render :edit
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_path

  end

  private

  def artist_params
    prams.require(:artist).permit(:name, :img_url)

  end


end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    before_action :set_song, only: [:edit, :update, :show, :destroy]
    # before_action :set_artist, only: [ :edit, :update,  :destroy]
    

  def index
    @songs  = Song.all
  end

  def show
    artist_id = @song.artist_id
    @artist = Artist.find(artist_id)

  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    artist_id = @song.artist_id
    @artist = Artist.find(artist_id)
    @songs = @artist.songs
      if @song.save
        respond_to do |format|
          format.html {redirect_to artist_path(@artist),notice: "Song succesfully created!" }
          format.js
        end

        # redirect_to artist_path(@artist), {notice: "Song succesfully created!" }
        #redirect_to song_path(@song), notice: "Song succesfully created"
      else
        render :edit
      end
  end



  def edit
  end

  def update

    if @song.update_attributes( song_params )
      redirect_to song_path(@song), notice: "Song succesfully updated"
    else
      render :edit
    end

  end

  def destroy
    artist_id = @song.artist_id
    @artist = Artist.find(artist_id)
    @song.destroy

    redirect_to artist_path(@artist)

  end

  private

  def song_params
    params.require(:song).permit(:name, :artist_id)

  end

  def set_song
    @song = Song.find(params[:id])
  end

  def set_artist
    @artist = @song.artist
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<!-- <div class="container"> -->
  <h1>Artists</h1>

  <ul class="sorting_links">
    <li><%= link_to "sort by name (asc)", :sort => "name", :direction => "asc" %></li>
    <li><%= link_to "sort by name (desc)", :sort => "name", :direction => "desc" %></li>
    <li><%= link_to "sort by date added (asc)", :sort => "created_at", :direction => "asc" %></li>
    <li><%= link_to "sort by date added (desc)", :sort => "created_at", :direction => "desc" %></li>
  </ul>


  <% @artists.each do | artist| %>
    <div class="artist-box">
    <a href="<%=artist_path(artist.id) %>"><img class="artist-thumb" src="<%=artist.img_url%>" alt = "<%= artist.name %>" ></a><br>
    <%= link_to artist.name, artist_path(artist.id) %><br>
    </div>
  <% end %>

<!-- </div>  -->

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<!-- <ul>
<% @songs.each do |song| %>
  <%if song.artist[:id] == @artist[:id]%>
  <li><%=song.name%></li>

  <%end%>
<%end%>
</ul> -->

<%= render "/songs/form"%>
<!-- link_to "[Delete_all]", -->

<ol id="songlist" >
  <%= render @songs %>
</ol>

<div>

<%= link_to "[Delete all songs]", artist_path(id: @artist.id), method: :delete, remote: true, data: { confirm: "Are you sure you want to delete all these songs?" } %>
<%= link_to "[Back to all artists]", artists_path() %>
</div>

app/views/artists/show.js.erb
$("#songform").submit(funciont(){
  alert('WHAAAAAAT, this gets executed? NOOOO WAY!!!!');

});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Songdb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

    <p id="notice"><%= notice %></p>

    <%= yield %>
    </div>


  <!-- <script>


  function submitSong(event) {
  // stop the form from doing the default action, submitting...
  event.preventDefault();
  // Declare a variable title,
  // and set it equal to whatever is the value of the element with id new-song
  var title = $("#new-song").val();
  // call the function CreateSong and give the title as its argument
  createSong(title);
  // select element with id new-song and clear its content
  $("#new-song").val(null);
  }


  // *** This function provides a new song id by counting all the elements
  // with class .song and adding 1 for the next id
  function nextSongId() {
    return $(".song").length + 1;
  }


  // *******************
  // *** This function creates a song and intiates a AJAX call to save it
  function createSong(title) {
    var songId = "song-" + nextSongId()
    // Declare a valiable ListItem and set is equal to...
    // (select all the list itmes on the page??)
    var listItem = $("<li></li>");
    // Add the class "song" to every list-item?
    listItem.addClass("song");

    // Declare a variable space
    // and set it equal to " " (TODO I don't get the syntax yet!!!)
    var space = document.createTextNode(" ");
    // Declare a variable label
    // and set it equal to page element <label></label>
    var label = $('<span id = "delete-songs" ></span>');
    // Add the title to the label
    label.html(title);
    // Append the label (with the title) to the new list item
    listItem.append(label);
    // Get the element wiht id songlist
    // Append the list item to the element with the id songlist
    $("#songlist").append( listItem );


    // var newSong = { name: title, artist_id: ???? };



    // $.ajax({
    //   type: "POST",
    //   url: "/songs.json",
    //   data: JSON.stringify({
    //       song: newSong
    //   }),
    //   contentType: "application/json",
    //   dataType: "json"
    // });


  }





  // This function deletes all songs with the .song class (so all songs)
  function deleteSongs(event) {
  event.preventDefault();
  $.when($(".song").remove());
  }








  $(document).ready(function(){
    // This binds the submitSong funtion to the form
    $("form").bind('submit', submitSong);

    $("#delete-all-songs").bind('click', deleteSongs);

    $("#delete-song").bind('click', deleteOneSong);
  });



</script> -->



  </body>
</html>

app/views/songs/_form.html.erb
<div class="form" id="songform">

  <%= form_for @song, remote: true do |i| %>
    <%= i.label "Songname" %>
    <%= i.text_field :name, placeholder: "Enter your song!" %>

     <%= i.hidden_field :artist_id, value: @artist.id %>

    <!-- If song is new, show Create button, else show Update button! -->
    <%= i.submit (@song.new_record? ? "Create" : "Update") %>

    
  <%end%>

</div>

app/views/songs/_song.html.erb
    <li class="song">
      <span > <%=song.name%> </span>
      <span class="delete-song"><%=link_to "delete", song_path(id: song.id), method: :delete, remote: true, data: { confirm: "Are you sure you want to delete this song?" }%></span>
    </li>

app/views/songs/create.js.erb
// alert('WHAAAAAAT, this gets executed? NOOOO WAY!!!!');

$("#songlist").html("<%= escape_javascript(render (@songs))%>")

app/views/songs/edit.html.erb
<h1>Edit Song</h1>
<%= render 'form' %>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Add a new song!</h1>
<%= render "form" %>

app/views/songs/show.html.erb
<h1> <%= @song.name %></h1>



<%= link_to "[edit song]", edit_song_path %>
<%= link_to "[Back to artist]", artist_path( @artist.id ) %>